version: '3'

services:
 myapplication:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5000"
   ports:
     - "5000:8080"
 db:
  image: postgres:15
  environment:
    POSTGRES_DB: "flaskdb_7uea"
    POSTGRES_USER: "admin"
    POSTGRES_PASSWORD: "yZqV5iPhvzOI9gPEVWVOfpV2zGm0DMXJ"