version: '3'

services:
 myapplication:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: "5000"
   ports:
     - "5000:8080"
 db:
  image: postgres:latest
  environment:
    POSTGRES_DB: "flaskdb"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "root"